-- Run this script as a DBA account such as SYSTEM.
ALTER USER fm IDENTIFIED BY oracle ACCOUNT UNLOCK;

GRANT CREATE SESSION TO fm;
GRANT CREATE TABLE TO fm;
GRANT CREATE VIEW TO fm;
GRANT CREATE SEQUENCE TO fm;
GRANT CREATE TRIGGER TO fm;
GRANT CREATE PROCEDURE TO fm;
GRANT UNLIMITED TABLESPACE TO fm;

ALTER SYSTEM REGISTER;
